### ISSUE TITLE
Cannot read property 'localPort' of undefined

### ISSUE THREAD

**Issue by jamesaspence** [Finanzchef24-GmbH/tunnel-ssh#23]
In trying to connect to a remote server, I have config that looks like this:

    var server = tunnel({
        remoteHost: '127.0.0.1',
        remotePort: 3306,
        localPort: 33333,
        verbose: true,
        sshConfig: {
            host: 'REMOTE-IP',
            username: 'USER',
            port: 22,
            privateKey: require('fs').readFileSync('/key/to/id_rsa'),
        }
    });

Every time I attempt to connect, it gives me the error `Cannot read property 'localPort' of undefined`.

What am I doing wrong here?

**Comment by agebrock** [comment]
Hmm, are u sure :) ? 
Tunnel does not get any config as far as i can guess here. 
Can you post your code please.

**Comment by kopertop** [comment]
The problem is with this code in index.js:

```
function tunnel(configArgs, callback) {

  try {
    var config = createConfig(configArgs);
  } catch (e) {
    callback(null, e);
  }

  return createServer(config).listen(config.localPort, config.localHost, callback);
}
```

You are defining *config* inside a try block but then using it outside the try block.

After fixing that, there are several other places where you're defining a variable in a lower-scope but using it elsewhere, like with "server". I think perhaps this is targeting an older version of node.js and is not working for those of us on later versions of node.

**Comment by agebrock** [comment]
Hi there, thanks for the hint. You are right, there is a "return" missing to exit the function before crashing. 
The forgotten server at the binding will be removed as well. 

What version of node  and plattform do you use ?

**Comment by agebrock** [comment]
If you did not manage to get it to work. Maybe you find hope in the next major. 
We will do some changes to the configuration.
