### ISSUE TITLE
Tunnel several ports

### ISSUE THREAD

**Issue by dimitarkolev** [Finanzchef24-GmbH/tunnel-ssh#38]
Is it possible to tunnel several ports with single connection to the server?

**Comment by agebrock** [comment]
Sorry that is not possible at the moment. I thought about implementing it but i did not see advantage over creating more that one instance. 
Do you need that feature for a specific reason ? 

We are releasing inject-tunnel-ssh later that day. With that package you are able to setup a array of tunnel instances on demand. Maybe that fits your usecase. 

Thanks for asking.

**Comment by netmiller** [comment]
Is this issue still not implemented? Or what do you mean by __inject-tunnel-ssh__, is it some different package?  My use-case is:  mostly my clients need tunnel for database (MariaDB) connection, but some clients have to do occasionally http(s) calls to the nginx-proxy on the same server. Nginx is needed for upstream connections (reverse proxy for specific reason; too long to explain).  Bare https-call is not adequate because ssh-tunnel will give stronger authentication (via using Yubikey4).
